### ISSUE TITLE
Not able to consume WCF with wsHttpBinding

### ISSUE THREAD

**Issue by neerajdwiv** [yaronn/wcf.js#10]
Config -
![image](https://cloud.githubusercontent.com/assets/13641031/9217938/4e6cd610-40eb-11e5-82a1-def84e8f8580.png)

Client code -

![image](https://cloud.githubusercontent.com/assets/13641031/9217947/67fd5712-40eb-11e5-9a6a-a5d3fef64c23.png)

It shows something for ctx in console but shows nothing for response. Please let me know, what I am missing?
I can able to consume this WCF service from a console application. Additional information is return type of this web method is XmlDocument. I dont know, this is matters or not ?

Output -
ctx :
![image](https://cloud.githubusercontent.com/assets/13641031/9218001/281394da-40ec-11e5-9172-1e0c1033bf31.png)

**Comment by yaronn** [comment]
your code seems ok. please use fiddler or some other proxy to see the soap that wcf.js sends and compare it to the soap c# sends.

**Comment by neerajdwiv** [comment]
Fiddler is not catching the requests made through wcf.js.

**Comment by yaronn** [comment]
glad you got it working!
