### ISSUE TITLE
Request for another example with WsHttpBinding

### ISSUE THREAD

**Issue by sinewave440hz** [yaronn/wcf.js#20]
Hi and thank you for this module and the ws module!

I turned to this solution as a node developer with no experience of .Net services. I suspect that many will do the same. With that in mind, could you provide another example for my use case? I am trying to connect to a third party service. I am in contact with the lead developer for that service and he has provided me with a very simple .Net client project that does exactly what I'm trying to do in js. So the issue for me is to essentially map that configuration to mine. Here's the config from the client project:

```
<?xml version="1.0" encoding="utf-8" ?>
<configuration>
    <startup> 
        <supportedRuntime version="v4.0" sku=".NETFramework,Version=v4.6.1" />
    </startup>
    <system.serviceModel>
        <bindings>
            <wsHttpBinding>
                <binding name="WSHttpBinding_IAppService">
                    <security>
                        <message clientCredentialType="UserName" />
                    </security>
                </binding>
            </wsHttpBinding>
        </bindings>
        <client>
            <endpoint address="http://app.parksandrecreation.com:12345/AppSvc.svc" binding="wsHttpBinding"
                bindingConfiguration="WSHttpBinding_IAppService" contract="AppServiceReference.IAppService"
                name="WSHttpBinding_IAppService">
                <identity>
                    <certificate encodedValue="jfjfj...." />
                </identity>
            </endpoint>
        </client>
    </system.serviceModel>
</configuration>
``` 

The client project contains a button which results in a call to the service method: 
```
                using (AppServiceReference.AppServiceClient client = new AppServiceReference.AppServiceClient())
                {
                    client.ClientCredentials.UserName.UserName = "user1";
                    client.ClientCredentials.UserName.Password = "pw1";
                    client.ClientCredentials.ServiceCertificate.Authentication.CertificateValidationMode = System.ServiceModel.Security.X509CertificateValidationMode.None;

                    sbProgress.AppendLine(DateTime.Now.TimeOfDay.ToString() + " Open");
                    client.Open();
                    sbProgress.AppendLine(DateTime.Now.TimeOfDay.ToString() + " Opened");

                    AppServiceReference.PARResult result = client.IsSvcRunning(99);
                    sbProgress.AppendLine(string.Format("Test={0} ({1}): {2}", (result.ResultCode == 1) ? "OK" : "FAIL", result.ResultCode.ToString(), result.ErrorMessage));

                    sbProgress.AppendLine(DateTime.Now.TimeOfDay.ToString() + " Close");
                    client.Close();
                    sbProgress.AppendLine(DateTime.Now.TimeOfDay.ToString() + " Closed");
                }
```

Here, then, is what I have so far that's not giving me any data back (I would expect a 1, as per what the test client receives):

```
var WSHttpBinding = require('wcf.js').WSHttpBinding,
    Proxy = require('wcf.js').Proxy,
    binding = new WSHttpBinding(
        { SecurityMode: "TransportWithMessageCredential",
            TransportClientCredentialType:"None",
            MessageClientCredentialType: "UserName"
        }),
    proxy = new Proxy(binding,"http://app.parksandrecreation.com:12345/AppSvc.svc"),
    message =  "<Envelope xmlns='http://schemas.xmlsoap.org/soap/envelope/'>" +
    "<Header />" +
    "<Body>" +
    "<IsSvcRunning xmlns='http://app.parksandrecreation.com'>" +
    "<value>99</value>" +
    "</IsSvcRunning>" +
    "</Body>" +
    "</Envelope>";

proxy.ClientCredentials.Username.Username = "user1";
proxy.ClientCredentials.Username.Password = "pw1";
console.log(message);
proxy.send(message, "http://app.parksandrecreation.com:12345/AppSvc.svc", function(response, ctx) {
    console.log("Anything? " + response);
});
```

Service names and credentials have of course been doctored here :) At the moment i am receiving an empty response, which is not what I expect.

**Comment by yaronn** [comment]
I think this binding uses .net specific features which are not interoperable outside, secifically certificate negotiation (negotiateServerCredential is by default true and not overriden here). It also uses secure conversation (establishSecureConversation=true by default) which is not .NEt specific but not supported by wcf.js yet. If you use Fiddler on the working .Net client and paste messages here or send me I can verify.

**Comment by sinewave440hz** [comment]
Don't have my windows machine available right now, but will do that when I do. What you are saying worries me a little - do you mean to say that the certificate negotiation features mean that I cannot call this service from anything except a .NET client? This could be a bit of a show stopper. As far as the secure conversation feature goes, I wonder whether your ws.js handles that? Or though you perhaps would have said so.

**Comment by yaronn** [comment]
correct, this service is not interoperable outside .Net. 
Also, ws.js does not support secure conversation. Even though some frameworks do support it (in jave for sure, don't think anything in js) it is still sometimes hard to fine tune everything.
Overall if interoperability is important I recommend to add another endpoint with transport security (ssl) which is much easier.

**Comment by sinewave440hz** [comment]
Thank you very much for your answers. I realise pursuing this further is possibly a little OT/outside scope, but perhaps you could arm me with the correct terminology to take the question wider. What is the specific feature that is .Net-specific? Is it ".Net Authentication" in itself, or something more specific like x509-certificate handling? Adding another endpoint to the service may be an option, but it is kind of asking our customer to do the work for us. The only other solution I can think of without specialist knowledge is some kind of .NET proxy that we build ourselves that receives on REST and sends on to the .NET service. Obviously this feels pretty hackish...

**Comment by yaronn** [comment]
just ask the customer to provide a sample soapui working request. soapui is the standard tool to test web services. if soapui cannot do it also then it is not interoperable.

see some more info here:

https://msdn.microsoft.com/en-us/library/ff647344.aspx#MessageSecurity6

**Comment by sinewave440hz** [comment]
Hi again. The service developer was able to set negotiateServiceCredential to false and has provided me with a certificate. Unsure how to proceed though, can wcf.js or ws.js help me? If not I will close the issue and look elsewhere I guess, but any pointers you can give would be very much appreciated!

**Comment by yaronn** [comment]
wcf.js cannot yet help, they should use basicHttpBinding or customBinding (so that wssecurity version 1.0 is used and not 1.1) and sign only (no message encryption). You can see some examples of supported bindings here https://github.com/yaronn/wcf.js/blob/master/test/integration/working-services/service-c%23/service/app.config. I don't think you will find any javascript implementation to support this yet, the best is if they can move to transport security (ssl) instead, possibly with username in the message for authenticaiton.

**Comment by sinewave440hz** [comment]
Ok, thank you. I will decide how to proceed, without wcf.js.

**Comment by sinewave440hz** [comment]
Hi again. The customer now has ssl set up. Am I right in thinking that 1) I can use wcf.js 2) I need to use BasicHttpBinding?
